#!/bin/bash

set -e

# =============================================================================
# ShipYard HTTPS Setup
# =============================================================================
# Obtains a Let's Encrypt certificate for this ShipYard instance and switches
# nginx to HTTPS with automatic renewal (certbot container, webroot challenge).
#
# Usage:
#   bash scripts/enable-https.sh yourdomain.com
#
# Requirements:
#   - The domain's DNS already points at this server (directly, or through a
#     proxy such as Cloudflare).
#   - HTTP_PORT is 80 (the Let's Encrypt HTTP challenge cannot use other ports).
#
# Rollback: delete docker-compose.override.yml and docker/nginx/conf.d-generated/
# then run "docker compose up -d" to return to plain HTTP.
# =============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1" >&2; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1" >&2; }
warning() { echo -e "${YELLOW}[WARNING]${NC} $1" >&2; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

if docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE="docker compose"
else
    DOCKER_COMPOSE="docker-compose"
fi

GENERATED_DIR="docker/nginx/conf.d-generated"
CERTBOT_DIR="docker/certbot"
OVERRIDE_FILE="docker-compose.override.yml"
TEMPLATE_DIR="docker/nginx/templates"

# --- Domain ---
DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
    printf "Domain pointing at this server: " >&2
    read DOMAIN </dev/tty
fi
if ! [[ "$DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$ ]]; then
    error "Invalid domain: $DOMAIN"
fi

# --- Email for the Let's Encrypt account ---
EMAIL=""
if [ -f backend/.env ]; then
    EMAIL=$(grep -E '^ADMIN_EMAIL=' backend/.env | head -1 | cut -d= -f2- | tr -d '"')
fi
if [ -z "$EMAIL" ]; then
    printf "Email for Let's Encrypt expiry notices: " >&2
    read EMAIL </dev/tty
fi
[ -z "$EMAIL" ] && error "An email address is required by Let's Encrypt."

# --- Preflight ---
[ -f "$TEMPLATE_DIR/https.conf.template" ] || error "Run this script from a ShipYard checkout (templates not found)."

HTTP_PORT=$(grep -E '^HTTP_PORT=' .env 2>/dev/null | cut -d= -f2)
HTTP_PORT="${HTTP_PORT:-80}"
if [ "$HTTP_PORT" != "80" ]; then
    error "HTTP_PORT is ${HTTP_PORT}. The Let's Encrypt HTTP challenge requires port 80."
fi

HTTPS_PORT=$(grep -E '^HTTPS_PORT=' .env 2>/dev/null | cut -d= -f2)
HTTPS_PORT="${HTTPS_PORT:-443}"
if [ "$HTTPS_PORT" != "443" ]; then
    error "HTTPS_PORT is ${HTTPS_PORT}. HTTPS setup requires the default port 443 (the redirect targets it)."
fi

if ! $DOCKER_COMPOSE ps nginx 2>/dev/null | grep -qE "Up|running"; then
    error "The nginx container is not running. Start the stack first: $DOCKER_COMPOSE up -d"
fi

if command -v getent >/dev/null 2>&1; then
    if ! getent hosts "$DOMAIN" >/dev/null 2>&1; then
        error "$DOMAIN does not resolve in DNS yet. Point it at this server, wait for propagation, and try again."
    fi
    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    RESOLVED_IP=$(getent hosts "$DOMAIN" | awk '{print $1}' | head -1)
    if [ -n "$SERVER_IP" ] && [ "$RESOLVED_IP" != "$SERVER_IP" ]; then
        warning "$DOMAIN resolves to $RESOLVED_IP, not this server's $SERVER_IP."
        warning "That is expected behind a proxy such as Cloudflare. Continuing."
    fi
fi

# Remember whether HTTPS state already existed so a failed FIRST run can roll
# back cleanly without destroying a previously working setup on a re-run.
FRESH_SETUP=true
[ -f "$OVERRIDE_FILE" ] && FRESH_SETUP=false

rollback() {
    if [ "$FRESH_SETUP" = true ]; then
        warning "Rolling back to plain HTTP..."
        rm -f "$OVERRIDE_FILE"
        rm -rf "$GENERATED_DIR"
        $DOCKER_COMPOSE up -d nginx >/dev/null 2>&1 || true
    fi
}

mkdir -p "$GENERATED_DIR" "$CERTBOT_DIR/conf" "$CERTBOT_DIR/www"

# --- Compose override: generated config, certbot mounts, renewal service ---
# Compose merges volume lists by container target, so only the new and
# replaced mounts appear here. The nginx command wrapper reloads config every
# 6h so renewed certificates are picked up automatically.
info "Writing ${OVERRIDE_FILE}..."
cat > "$OVERRIDE_FILE" << 'EOF'
# Generated by scripts/enable-https.sh. Not tracked by git.
# Delete this file plus docker/nginx/conf.d-generated/ and run
# "docker compose up -d" to return to plain HTTP.
services:
  nginx:
    command: /bin/sh -c 'while :; do sleep 6h; nginx -s reload; done & exec nginx -g "daemon off;"'
    volumes:
      - ./docker/nginx/conf.d-generated/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: server-mgmt-certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done'
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    networks:
      - server-mgmt
EOF

# --- Phase 1: obtain the certificate over HTTP ---
if [ -f "$CERTBOT_DIR/conf/live/$DOMAIN/fullchain.pem" ]; then
    info "Certificate for $DOMAIN already exists, skipping issuance."
else
    info "Configuring nginx for the ACME challenge..."
    cp "$TEMPLATE_DIR/http-acme.conf.template" "$GENERATED_DIR/default.conf"
    $DOCKER_COMPOSE up -d nginx

    info "Requesting a certificate for $DOMAIN from Let's Encrypt..."
    if ! $DOCKER_COMPOSE run --rm --entrypoint certbot certbot certonly \
        --webroot -w /var/www/certbot \
        -d "$DOMAIN" \
        --email "$EMAIL" \
        --agree-tos --no-eff-email --non-interactive; then
        rollback
        error "Certificate request failed. Common causes: DNS not propagated yet, a firewall blocking port 80, or Let's Encrypt rate limits.\nFix the cause, then run: bash scripts/enable-https.sh $DOMAIN"
    fi
fi

# --- Phase 2: switch nginx to HTTPS ---
info "Switching nginx to HTTPS..."
sed "s/{{DOMAIN}}/$DOMAIN/g" "$TEMPLATE_DIR/https.conf.template" > "$GENERATED_DIR/default.conf"
$DOCKER_COMPOSE up -d nginx certbot

if ! $DOCKER_COMPOSE exec -T nginx nginx -t; then
    rollback
    error "The generated nginx config failed validation."
fi
$DOCKER_COMPOSE exec -T nginx nginx -s reload

# --- Point Laravel at the domain ---
info "Updating backend/.env..."
sed -i "s|^APP_URL=.*|APP_URL=https://$DOMAIN|" backend/.env
if ! grep -E '^SANCTUM_STATEFUL_DOMAINS=' backend/.env | grep -q "$DOMAIN"; then
    sed -i "s|^SANCTUM_STATEFUL_DOMAINS=.*|&,$DOMAIN|" backend/.env
fi

info "Refreshing Laravel caches..."
$DOCKER_COMPOSE exec -T -w /var/www/html app php artisan optimize:clear >/dev/null
$DOCKER_COMPOSE exec -T -w /var/www/html app php artisan config:cache >/dev/null
$DOCKER_COMPOSE exec -T -w /var/www/html app php artisan route:cache >/dev/null
$DOCKER_COMPOSE restart app queue scheduler >/dev/null 2>&1

# --- Verify against the origin directly (bypasses any proxy in front) ---
info "Verifying HTTPS on the origin..."
if curl -fsS --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN/health" >/dev/null 2>&1; then
    success "HTTPS is answering on this server."
else
    warning "Could not verify https://$DOMAIN/health locally. Check: $DOCKER_COMPOSE logs nginx"
fi

echo "" >&2
success "HTTPS enabled for $DOMAIN"
echo "" >&2
echo "  Dashboard:  https://$DOMAIN/app" >&2
echo "  Renewal:    automatic (certbot container checks every 12h)" >&2
echo "" >&2
echo "  Plain HTTP now redirects to HTTPS." >&2
echo "  If this domain sits behind Cloudflare, set its SSL/TLS mode to" >&2
echo "  \"Full (strict)\" now. Staying on Flexible causes a redirect loop." >&2
echo "" >&2
